export enum Role {
  SUPER_ADMIN = 'super_admin',
  SP = 'sp',
  DSP = 'dsp',
  NAGERCOIL_ADMIN = 'nagercoil_admin',
  THUCKALAY_ADMIN = 'thuckalay_admin',
  COLACHEL_ADMIN = 'colachel_admin',
  KANYAKUMARI_ADMIN = 'kanyakumari_admin',
  MARTHANDAM_ADMIN = 'marthandam_admin',
  INSPECTOR = 'inspector',
  SUB_INSPECTOR = 'sub_inspector',
  OPERATOR = 'operator',
  VIEWER = 'viewer',
  DEVELOPER = 'developer',
}
